// <auto-generated />
using System;
using Labb2Linq.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Labb2Linq.Migrations
{
    [DbContext(typeof(SkolaDbContext))]
    [Migration("20220225140646_update")]
    partial class update
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Labb2Linq.Elev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("_KlassId")
                        .HasColumnType("int");

                    b.Property<string>("efterNamn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("förNamn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("_KlassId");

                    b.ToTable("Elever");
                });

            modelBuilder.Entity("Labb2Linq.Klass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("klassNamn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Klasser");
                });

            modelBuilder.Entity("Labb2Linq.Kurs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("_KlassId")
                        .HasColumnType("int");

                    b.Property<int?>("_LärareId")
                        .HasColumnType("int");

                    b.Property<string>("kursNamn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("_KlassId");

                    b.HasIndex("_LärareId");

                    b.ToTable("Kurser");
                });

            modelBuilder.Entity("Labb2Linq.Lärare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("efterNamn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("förNamn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Lärare");
                });

            modelBuilder.Entity("Labb2Linq.Elev", b =>
                {
                    b.HasOne("Labb2Linq.Klass", "_Klass")
                        .WithMany("Elever")
                        .HasForeignKey("_KlassId");
                });

            modelBuilder.Entity("Labb2Linq.Kurs", b =>
                {
                    b.HasOne("Labb2Linq.Klass", "_Klass")
                        .WithMany("Kurser")
                        .HasForeignKey("_KlassId");

                    b.HasOne("Labb2Linq.Lärare", "_Lärare")
                        .WithMany("Kurser")
                        .HasForeignKey("_LärareId");
                });
#pragma warning restore 612, 618
        }
    }
}
